version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: links
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    depends_on: 
      - db