version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  
  app:
    build:
      context: ./build/service/
      dockerfile: Dockerfile
    ports: 
      - "8088:8088"
    depends_on: 
      - db